/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'badge' : IDL.Text,
  'brand' : IDL.Text,
  'price' : IDL.Nat,
  'stockQty' : IDL.Nat,
  'inStock' : IDL.Bool,
});
export const Enquiry = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addProduct' : IDL.Func([IDL.Text, Product], [IDL.Bool], []),
  'checkAdminPassword' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'deleteEnquiry' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'deleteProduct' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'getAllStock' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
      [],
    ),
  'getEnquiries' : IDL.Func([IDL.Text], [IDL.Vec(Enquiry)], []),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], []),
  'getProductStock' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], []),
  'seedProducts' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'setProductStock' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'submitEnquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'updateProduct' : IDL.Func([IDL.Text, IDL.Nat, Product], [IDL.Bool], []),
});

export const idlInitArgs = [];
export const idlFactory = ({ IDL }) => idlService;
export const init = ({ IDL }) => { return []; };
